### ISSUE TITLE
The user-defined fixed time-step `dt` is not respected in `_fixed_odeint`

### ISSUE THREAD

**Issue by pierreguilmin** [pierreguilmin/torchqdynamics#27]
We discussed this issue with @gautierronan [here](https://github.com/PierreGuilmin/torchqdynamics/pull/21#discussion_r1141026169), in summary we agreed to _modify_ the `dt` used within `_fixed_odeint` to prevent errors of order `dt` on the evolution when `t_save[-1]` is not a perfect multiple of `dt`. However, I just realized that the `MERouchon` routines uses the original `dt` set by the user, and not the updated `dt`.

**Comment by PierreGuilmin** [comment]
cc @gautierronan

**Comment by gautierronan** [comment]
To be fair I have no idea how to fix this. If the user gives `dt = 0.1` but also `t_save = torch.linspace(0. ,1., 11)`, then the user is right: his `t_save` values **are** aligned with `dt`. But they're actually not because `torch.linspace` has some 1e-6 error. 

So the correct thing I think is what we're doing already: saving the result at exact multiples of `dt`.

**Comment by gautierronan** [comment]
After some investigation, I actually figured out that you should specify `torch.linspace(..., dtype=torch.float64)` when calling linspace. Otherwise it assumes the default dtype, which is float32. Maybe we should:

1. Make the t_save/dt "alignement" condition more strict (instead of `rtol=1e-5`, take `rtol=1e-10`)
2. When raising the error, tell users to be careful with `torch.linspace`'s default dtype

**Comment by pierreguilmin** [comment]
Related: #86.
